framerate_final="14"
inres="1440x900" # input resolution
outres="1440" # output resolution horizontal. vertical is calculated. 
gop="96" # i-frame interval, should be double of FPS, 
threads="2" # max 6
cbr="1174k" # constant bitrate (should be between 1000k - 3000k)
quality="veryfast"  # ultrafast superfast veryfast faster fast medium slow slower veryslow placebo

[audio]
audio_srate="22050"
audio_channels="2" #1 for mono output, 2 for stereo
audio_erate="128k" #audio encoding rate
audio_dev="-f alsa -i pulse" # -i hw:CARD=0,DEV=0
audio_codec="libmp3lame"
pulseaudio_params="$AUDIO_DEV -ac $AUDIO_CHANNELS -b:a $AUDIO_ERATE -ar $AUDIO_SRATE"

[screen]
i=":0.0+0,0"
# Apis are opencl vdpau vaapi libmfx nvenc drm
hwaccelapi="-hwaccel vdpau -f x11grab"

[stream]
stream_key="" #your twitch stream key goes here
server="mia" # rio atl sao mia mia05  http://bashtech.net/twitch/ingest.php for list
videocodec="libx264"
target="rtmp://$SERVER.contribute.live-video.net/app/$STREAM_KEY"
target_local="-listen 2 rtmp://192.168.2.45"
target_null="-y /dev/null"
outfmt="flv"
